### ISSUE TITLE
get_area_def balks if proj4_args is unicode

### ISSUE THREAD

**Issue by boojums** [mraspaud/pyresample#24]
If the proj4 string passed to utils.get_area_def() is of type unicode instead of type str then the user gets RuntimeError: no projection control parameters specified.

Seems to me either _get_proj4_args() should try to handle the unicode or a more helpful error should be raised. 

This is the string pulled from a netCDF file that made get_area_def() barf: 
u'+proj=stere +a=6378273 +b=6356889.44891 +lat_0=90 +lat_ts=70 +lon_0=-45'

**Comment by mraspaud** [comment]
Yes, I agree, pyresample should handle unicode. Which version of python are you using ?

**Comment by boojums** [comment]
This is with 2.7.3

**Comment by mraspaud** [comment]
@boojums could you check if it does work now ? (pre-master branch)

**Comment by boojums** [comment]
Yes, that works. Next time there's something quick like this would you prefer a pull request with the issue?

**Comment by mraspaud** [comment]
Yes, that would be great :)
